// @ts-check
import { indexRecordContent, validateRecordContent } from './record-model.js';

export const recordContent = validateRecordContent({
  projects: [
    {
      id: 'wellbeing-studio-2027',
      path: '/work/wellbeing-studio',
      title: 'Wellbeing Studio 2027',
      organisation: 'Corporate Yoga Australia',
      period: '2026–27',
      state: 'Active',
      proposition: 'Redesigning a workplace wellbeing platform around the moments people actually have during a working day, then connecting those useful actions into a service that can continue beyond a single visit.',
      context: 'Wellbeing Studio already operates as a live member experience combining programming, live sessions and an on-demand practice library. The 2027 work reframes that product beyond a content portal and asks how entry, continuity and evidence should behave as one connected service.',
      role: 'Product strategy, experience architecture, UX/UI, learning technology and implementation',
      altitude: 'Product · experience · system',
      trajectory: [
        {
          period: 'Live foundation',
          label: 'A service became a product',
          detail: 'Weekly programming, live sessions and an on-demand library moved into one member experience with repeatable publishing and onboarding workflows.',
        },
        {
          period: '2026',
          label: 'The product was reframed',
          detail: 'The redesign stopped treating the library, live program and campaign experiences as separate destinations and began designing around useful moments in working life.',
        },
        {
          period: '2026',
          label: 'Entry became contextual',
          detail: 'Before Work, During Work and After Work became the primary lens for the Practice Library, with need, practice type and duration remaining available as secondary refinement.',
        },
        {
          period: '2027 direction',
          id: 'connected-service',
          label: 'Useful action becomes continuity',
          detail: 'The product model widened from content discovery to a connected service: Action, Return and Explore lead to useful experiences, with human-led activity, campaigns, programs and personal continuity connected only where they add value.',
        },
      ],
      recordIds: ['ws-contextual-entry', 'ws-connected-service', 'ws-ruok-production-slice'],
      placements: [{ surface: 'work', order: 1, role: 'anchor', featured: true }],
    },
    {
      id: 'connect-and-learn',
      path: '/work/connect-and-learn',
      title: 'ISQ Connect & Learn',
      organisation: 'Independent Schools Queensland',
      period: '2024',
      state: 'Completed',
      proposition: 'A professional learning platform migration and more than sixty Storyline course rebuilds carried through the same three-month engagement.',
      context: 'A platform, content estate and production problem that had to be solved together rather than handed from one discipline to the next.',
      role: 'Platform migration, learning architecture and eLearning development',
      altitude: 'Experience · content · platform',
      trajectory: [],
      recordIds: [],
      placements: [{ surface: 'work', order: 2, role: 'anchor' }],
    },
    {
      id: 'casa-ferc',
      path: '/work/casa/flight-examiner-rating',
      title: 'CASA Flight Examiner Rating Course',
      organisation: 'Civil Aviation Safety Authority',
      period: '2015–21',
      state: 'Completed',
      proposition: 'Regulated professional learning designed for people whose work depends on judgement, not recall.',
      context: 'Part of six years designing learning, platforms, production systems and media inside Australia’s aviation safety regulator.',
      role: 'Learning design, interaction design, Storyline development and media production',
      altitude: 'Artefact · experience · system',
      trajectory: [],
      recordIds: ['casa-examiner-judgement'],
      placements: [{ surface: 'work', order: 3, role: 'anchor' }],
    },
    {
      id: 'tafe-pathways',
      path: '/work/tafe-pathways',
      title: 'TAFE Queensland SkillsTech Pathways',
      organisation: 'TAFE Queensland SkillsTech',
      period: '2015',
      state: 'Historical',
      proposition: 'An interactive careers experience designed to support a conversation with a careers adviser rather than replace it.',
      context: 'A facilitator-led platform for Years 8–9 school sessions, using Storyline well beyond a conventional linear module.',
      role: 'Project lead, interaction design and Storyline development',
      altitude: 'Artefact · experience',
      trajectory: [],
      recordIds: ['tafe-supported-conversation'],
      placements: [{ surface: 'work', order: 4, role: 'anchor' }],
    },
  ],
  records: [
    {
      id: 'ws-contextual-entry',
      projectId: 'wellbeing-studio-2027',
      path: '/work/wellbeing-studio/contextual-entry',
      title: 'Designing entry around moments in the working day',
      centre: 'Contextual entry',
      context: 'Wellbeing Studio 2027 · Practice Library',
      happened: 'The Practice Library was reorganised around Before Work, During Work and After Work. A “Right now” prompt surfaces one useful starting point, while need, practice type and duration remain available for deliberate refinement.',
      worthExamining: 'A library can contain excellent material and still create work for the person using it. The design move was to make the current moment the first question, reducing the distance between “I need something” and a practice that fits.',
      tension: 'A conventional content library starts by asking people to browse categories. That is useful when someone knows what they want. It is weaker when they have three minutes between meetings and only know how they feel.',
      move: 'Make day stage the primary lens rather than another filter. Use the local moment to create a believable default, then leave the wider taxonomy available for people who want to browse or plan ahead.',
      making: [
        'Before Work, During Work and After Work form the persistent day-stage structure.',
        '“Right now” surfaces one suggested practice without requiring a filter decision first.',
        'Need, practice type and duration remain secondary refinements rather than disappearing.',
        'The mobile composition keeps the same architecture, recomposed as day-stage tabs, a compact Refine action and a vertical practice list.',
      ],
      evidenceBoundary: 'This Record demonstrates the product decision, the designed interaction and its implementation constraints. It does not claim participant-use, retention or wellbeing outcomes for this interaction.',
      artefactIds: ['ws-daily-wellbeing-journey'],
      evidenceClaimIds: ['ws-live-foundation', 'ws-contextual-intent', 'ws-contextual-implementation'],
      relationships: [
        {
          id: 'ws-entry-led-to-continuity',
          verb: 'led-to',
          label: 'the connected-service model',
          href: '/work/wellbeing-studio/connected-service',
          note: 'Once entry is designed around a useful moment, the next question is what the Studio should remember, connect and make available afterwards.',
        },
      ],
    },
    {
      id: 'ws-connected-service',
      projectId: 'wellbeing-studio-2027',
      path: '/work/wellbeing-studio/connected-service',
      title: 'From content portal to connected wellbeing service',
      centre: 'Product reframe',
      context: 'Wellbeing Studio 2027 · Product strategy and experience architecture',
      happened: 'The redesign stopped treating Wellbeing Studio as a set of destinations such as Home, Practice Library, Live and My Studio. Participant situations and journeys were used to derive a behavioural model — Action, Return and Explore — with Useful Experience at the centre and campaigns, programs, human-led experiences and continuity connected around it.',
      worthExamining: 'This was not a navigation tidy-up. Changing the unit of design from pages and content types to useful participant experiences changed what the product is, what deserves persistence, when identity matters and how digital activity connects to CYA’s human service.',
      tension: 'The existing implementation already contained useful pages, navigation and technical infrastructure. Preserving those structures by default would have let the prototype define the product: a familiar content portal with live and personal areas attached.',
      move: 'Start from real working situations, CYA encounters and return behaviour. Let Action minimise the distance to something useful, Return make trusted experiences easy to retrieve, and Explore support deliberate browsing without organising the whole product around a catalogue.',
      making: [
        'Action, Return and Explore became behavioural modes rather than proposed navigation labels.',
        'Useful Experience became the centre of participant value; a successful journey may legitimately end there.',
        'Human-led and digital experiences were placed inside one CYA service ecosystem rather than treated as separate channels.',
        'Campaigns, programs and physical CYA encounters became contextual entry conditions capable of deep-linking into the same product.',
        'Continuity was made proportionate and earned: recent, saved, practitioner, live and program relationships matter only where they create participant value.',
        'Authentication was reframed as an interruption that must preserve original intent rather than a destination participants should be sent to.',
      ],
      evidenceBoundary: 'This Record supports the adopted product and experience architecture and the reasoning that produced it. It does not claim that the full connected-service model has been implemented or validated with participants; those remain separate evidence questions.',
      artefactIds: ['ws-connected-service-map'],
      evidenceClaimIds: ['ws-service-layer-definition', 'ws-action-return-explore', 'ws-human-connected', 'ws-earned-continuity'],
      relationships: [
        {
          id: 'ws-service-proved-through-ruok',
          verb: 'continued-in',
          label: 'the R U OK? Day production slice',
          href: '/work/wellbeing-studio/ruok-production-slice',
          note: 'The broader connected-service architecture was deliberately reduced to a bounded campaign slice so the product could be proven without attempting to ship every future capability.',
        },
      ],
    },

    {
      id: 'ws-ruok-production-slice',
      projectId: 'wellbeing-studio-2027',
      path: '/work/wellbeing-studio/ruok-production-slice',
      title: 'Taking R U OK? Day through a production vertical slice',
      centre: 'Production implementation',
      context: 'Wellbeing Studio 2027 · R U OK? Day Production Pilot 01',
      happened: 'R U OK? Day was chosen as the first bounded production release of Wellbeing Studio 2027. The work moved from a defined campaign slice into a real application route, then through participant-access, staging, Magic Link remediation, content integration and runtime-reliability work. Later product specification deliberately removed mandatory authentication from the RUOK core journey, retaining the proven infrastructure without allowing it to dictate participant behaviour.',
      worthExamining: 'The useful evidence is not simply that a campaign page was built. It is the sequence of product definition, vertical-slice implementation, production qualification and subsequent correction: engineering proved what the platform could do, while product architecture retained the authority to decide what participants should actually be required to do.',
      tension: 'The campaign had a fixed 10 September date and substantial infrastructure already existed. The risk ran in both directions: throw away proven foundations and build a disposable microsite, or preserve every existing capability — including authentication and inherited navigation — simply because it had already been engineered.',
      move: 'Use R U OK? Day as a constrained production proof inside the real Studio. Extend durable content, media, database, deployment and access foundations; qualify them in deliberate gates; then re-evaluate each capability against participant value rather than treating implementation as product authority.',
      making: [
        'Commit 2c56d6b established the R U OK? Day Experience vertical slice inside the production application.',
        'Run 02 added Neon Auth and participant authentication while preserving the existing Proof 06D operational foundations.',
        'Run 03 established staging participant-access readiness; commit 0efb911 then fixed Magic Link redemption that could strand an authenticated participant on the sign-in route.',
        'The production branch was hardened for staging Postgres reliability at c6a23a8 rather than accepting local success as production proof.',
        'Launch Candidate 1 content integration progressed separately through 1892158, d57e18b and 72966d4, including media-integrity remediation before production reconciliation.',
        'The later canonical RUOK Product Specification removed mandatory authentication, registration and profile behaviour from the core campaign journey: keep the engine, redraw the product around it.',
      ],
      evidenceBoundary: 'This Record supports the existence and sequence of the production slice, participant-access proof, staging/reliability work and later product correction. It does not claim the 10 September campaign has occurred, that participant outcomes have been measured, or that every launch gate is already closed.',
      artefactIds: ['ws-ruok-production-gates'],
      evidenceClaimIds: ['ws-ruok-slice-definition', 'ws-ruok-vertical-slice', 'ws-ruok-production-hardening', 'ws-ruok-auth-correction'],
      relationships: [],
    },

    {
      id: 'casa-examiner-judgement',
      projectId: 'casa-ferc',
      path: '/work/casa/flight-examiner-rating/examiner-judgement',
      title: 'Designing for examiner judgement rather than recall',
      centre: 'Assessment reasoning',
      context: 'CASA Flight Examiner Rating Course · regulated professional learning',
      happened: 'The Flight Examiner Rating course was designed for air transport, helicopter and general aviation examiners — experienced assessors who test the people who train and test other pilots. The learning made regulatory hierarchy, principles of assessment and the broader dimensions of competency visible as connected reasoning structures rather than treating the regulation as content to restate.',
      worthExamining: 'The audience already worked with regulation and assessment. Generic compliance treatment would have reduced credibility and attention. The design problem was how to preserve regulatory accuracy while giving senior practitioners structures they could recognise and apply in assessment judgement.',
      tension: 'Restating the regulation accurately produces a document rather than a learning program. Simplifying until it is easy risks becoming untrue. In a safety-regulated domain, that is not merely an editorial weakness.',
      move: 'Treat the examiner’s reasoning as the centre of the experience. Show which instrument governs, establish a shared model of assessment quality, and make the dimensions of competency visible beyond the single task an examiner can observe directly.',
      making: [
        'The Civil Aviation Act, regulations, orders, Part 61 licensing, Manual of Standards and Flight Examiner Handbook were mapped as an instrument hierarchy rather than presented as unrelated references.',
        'Validity, reliability, flexibility and objectivity were made explicit as principles for judging assessment quality.',
        'The four dimensions of competency were visualised so task skills could be considered alongside task management, contingency management and job-role environment skills.',
        'Scenario and assessment design was grounded in the regulatory instrument hierarchy rather than separated from it.',
        'Responsive delivery was treated as part of the learning context because examiners work at aerodromes and in aircraft, not only at desks.',
      ],
      evidenceBoundary: 'This Record supports the audience, design intent, assessment structure and recovered course artefacts. It does not claim participant numbers, evaluation results or measured program outcomes, which are not published in the source record.',
      artefactIds: ['casa-assessment-reasoning-sequence'],
      evidenceClaimIds: ['casa-examiner-audience', 'casa-reasoning-design', 'casa-assessment-principles', 'casa-competency-model'],
      relationships: [],
    },

    {
      id: 'tafe-supported-conversation',
      projectId: 'tafe-pathways',
      path: '/work/tafe-pathways/supporting-conversation',
      title: 'Designing technology to support a conversation, not replace it',
      centre: 'Facilitated exploration',
      context: 'TAFE Queensland SkillsTech Pathways · Years 8–9 careers sessions',
      happened: 'Pathways was designed for facilitated Years 8–9 school sessions. Students and a TAFE careers adviser could move non-linearly through industry data, job profiles, workplace imagery, maps and summaries rather than following a prescribed module sequence. The technology gave the adviser a shared environment to explore with the group rather than attempting to automate the adviser’s role.',
      worthExamining: 'Digital careers products often assume the goal is self-service. This project had a human expert already in the experience. The consequential design decision was to make the software expand what that person could show, compare and discuss instead of treating the conversation as friction to remove.',
      tension: 'A self-directed careers flow can answer a sequence of predefined questions efficiently, but it also decides the sequence before the room has spoken. In a facilitated school session, that risks turning the adviser into someone who advances slides rather than someone who follows curiosity.',
      move: 'Build an explorable information environment with persistent navigation and several parallel modes. Keep industry data, career profiles, workplace context and summaries close enough that the facilitator can change direction when a question emerges without losing the shared frame.',
      making: [
        'Five persistent modes — Home, Industry Data, Job Profiles, Slideshow and Summary — supported movement without forcing a single sequence.',
        'Industry-level navigation and approximately twenty careers created breadth without flattening every career into one long list.',
        'Job profiles were placed into an interactive map/environment so careers could be discussed spatially and visually.',
        'Comparable industry data created stable reference points; JavaScript dynamically counted the statistics in response to a SkillsTech team request.',
        'Extensive Storyline variables maintained state across the experience, helping the piece behave more like an application than a slide-based module.',
        'Glenn led the project and engaged former colleague Elisha Gillett to work with him.',
      ],
      evidenceBoundary: 'This Record supports the facilitator-led purpose, the non-linear information architecture, the recovered interface evidence and the implementation characteristics documented in the editorial inventory. It does not claim enrolment, career-choice or session-effectiveness outcomes.',
      artefactIds: ['tafe-facilitated-exploration'],
      evidenceClaimIds: ['tafe-facilitated-purpose', 'tafe-parallel-modes', 'tafe-spatial-exploration', 'tafe-stateful-storyline'],
      relationships: [],
    },
  ],
  artefacts: [
    {
      id: 'ws-daily-wellbeing-journey',
      recordId: 'ws-contextual-entry',
      path: '/work/wellbeing-studio/contextual-entry/daily-wellbeing-journey',
      title: 'Daily wellbeing journey',
      kind: 'Interaction concept',
      provenance: 'Wellbeing Studio Practice Library · Concept C',
      status: 'Designed evidence',
      summary: 'A desktop and mobile interaction model that makes day stage the primary entry point into the Practice Library and keeps need, practice type and duration as secondary refinement.',
      accessibility: 'The inspection below reconstructs the interaction semantically in HTML so the evidence remains understandable without relying on the original visual concept image.',
      evidenceClaimIds: ['ws-contextual-intent', 'ws-contextual-implementation'],
    },
    {
      id: 'ws-connected-service-map',
      recordId: 'ws-connected-service',
      path: '/work/wellbeing-studio/connected-service/relationship-model',
      title: 'Connected service relationship model',
      kind: 'Product architecture',
      provenance: 'WS27 Experience Architecture · Product Blueprint v1',
      status: 'Architectural evidence',
      summary: 'A non-linear product model showing how real working situations and CYA encounters enter through Action, Return or Explore, resolve in a Useful Experience, and connect to human-led activity, campaigns, programs or personal continuity only when useful.',
      accessibility: 'The model is reconstructed as ordered semantic groups rather than a flattened diagram image, preserving its relationships for keyboard, enlarged-text and assistive-technology use.',
      evidenceClaimIds: ['ws-service-layer-definition', 'ws-action-return-explore', 'ws-human-connected', 'ws-earned-continuity'],
    },

    {
      id: 'ws-ruok-production-gates',
      recordId: 'ws-ruok-production-slice',
      path: '/work/wellbeing-studio/ruok-production-slice/qualification-map',
      title: 'R U OK? Day production qualification map',
      kind: 'Production evidence',
      provenance: 'Wellbeing Studio Production Pilot 01 · August 2026',
      status: 'Implemented and qualified evidence',
      summary: 'A production-history map showing how a bounded campaign definition became a technical vertical slice, participant-access proof, staging and runtime hardening, parallel launch-candidate content integration, and finally a product correction that kept proven infrastructure while removing mandatory authentication from the core RUOK journey.',
      accessibility: 'The production history is represented as semantic staged evidence with explicit commit identifiers, branch relationships and product corrections rather than as a flattened Git graph screenshot.',
      evidenceClaimIds: ['ws-ruok-slice-definition', 'ws-ruok-vertical-slice', 'ws-ruok-production-hardening', 'ws-ruok-auth-correction'],
    },

    {
      id: 'casa-assessment-reasoning-sequence',
      recordId: 'casa-examiner-judgement',
      path: '/work/casa/flight-examiner-rating/examiner-judgement/assessment-reasoning',
      title: 'Assessment reasoning sequence',
      kind: 'Course evidence',
      provenance: 'CASA Flight Examiner Rating Course · recovered production artefacts',
      status: 'Implemented evidence',
      summary: 'Three course artefacts showing the progression from regulatory instrument hierarchy, through principles of assessment, to the four dimensions of competency that inform examiner judgement.',
      accessibility: 'Each recovered course image is presented with intrinsic dimensions, responsive sources, descriptive alt text and an explanatory caption so the evidentiary sequence remains understandable without depending on the screenshot alone.',
      evidenceClaimIds: ['casa-reasoning-design', 'casa-assessment-principles', 'casa-competency-model'],
    },

    {
      id: 'tafe-facilitated-exploration',
      recordId: 'tafe-supported-conversation',
      path: '/work/tafe-pathways/supporting-conversation/exploration-environment',
      title: 'Facilitated exploration environment',
      kind: 'Historical interaction evidence',
      provenance: 'TAFE Queensland SkillsTech Pathways · recovered 2015 artefacts',
      status: 'Historical evidence',
      summary: 'Recovered Pathways artefacts showing the non-linear wireframe, comparable industry data, category-filtered workplace map and persistent visual exploration modes used to support a facilitator-led careers conversation.',
      accessibility: 'Each historical interface image is presented with responsive sources, intrinsic dimensions, descriptive alt text and contemporary editorial framing. The original visual treatment is preserved rather than redesigned.',
      evidenceClaimIds: ['tafe-facilitated-purpose', 'tafe-parallel-modes', 'tafe-spatial-exploration', 'tafe-stateful-storyline'],
    },
  ],
  evidenceClaims: [
    {
      id: 'ws-live-foundation',
      state: 'implemented',
      claim: 'The existing Wellbeing Studio combines weekly programming, live sessions and an on-demand practice library in one member experience.',
      basis: 'Existing Wellbeing Studio project record and operating-platform evidence.',
      limitation: 'This claim describes the live foundation, not the 2027 contextual-entry redesign.',
    },
    {
      id: 'ws-contextual-intent',
      state: 'intended',
      claim: 'Day stage is the primary lens so a participant can begin from the moment they are in rather than from a content category.',
      basis: 'Practice Library Concept C: Daily Wellbeing Journey.',
      limitation: 'The concept defines the intended interaction; participant behaviour has not been claimed as validated.',
    },
    {
      id: 'ws-contextual-implementation',
      state: 'intended',
      claim: 'The “Right now” state can use the visitor’s local clock, while day-stage tabs and client-side filtering remain compatible with the current Moodle environment.',
      basis: 'Practice Library Concept C implementation notes.',
      limitation: 'The source establishes implementation feasibility, not measured product impact.',
    },
    {
      id: 'ws-service-layer-definition',
      state: 'intended',
      claim: 'Wellbeing Studio 2027 is defined as CYA’s digital service layer for connecting people with useful wellbeing experiences from real working-life situations, CYA encounters and ongoing service relationships.',
      basis: 'WS27 Product Blueprint v1 and consolidated Interaction Architecture.',
      limitation: 'This is the adopted product architecture; it does not assert that every experience family is already implemented.',
    },
    {
      id: 'ws-action-return-explore',
      state: 'intended',
      claim: 'Action, Return and Explore are the core behavioural modes, with Useful Experience at the centre rather than a conventional content catalogue or dashboard.',
      basis: 'WS27 Phase 2 discovery, Phase 3A information architecture and Product Blueprint v1.',
      limitation: 'The model is architectural product evidence, not participant-validation evidence.',
    },
    {
      id: 'ws-human-connected',
      state: 'intended',
      claim: 'Digital practices, human-led experiences, workplace delivery, campaigns and programs belong to one connected CYA service ecosystem.',
      basis: 'WS27 Phase 2 and Phase 3A product strategy and experience architecture.',
      limitation: 'The architecture establishes the intended relationship; implementation maturity varies by experience.',
    },
    {
      id: 'ws-earned-continuity',
      state: 'intended',
      claim: 'Continuity is useful only when it creates participant value; successful journeys may end without forcing sign-in, progress, follow-up or a dashboard state.',
      basis: 'WS27 Interaction Architecture and Product Blueprint continuity principles.',
      limitation: 'Specific continuity mechanics remain subject to product-slice implementation and participant validation.',
    },

    {
      id: 'ws-ruok-slice-definition',
      state: 'intended',
      claim: 'R U OK? Day was defined as the first bounded production slice of Wellbeing Studio 2027 rather than a launch of the full future product.',
      basis: 'Definitive Product Definition — R U OK? Day Experience Production Pilot 01 v1.1 and subsequent RUOK Product Specification.',
      limitation: 'The exact participant contract evolved after the initial pilot definition, particularly around mandatory authentication.',
    },
    {
      id: 'ws-ruok-vertical-slice',
      state: 'implemented',
      claim: 'A real R U OK? Day Experience vertical slice was implemented in the Wellbeing Studio production codebase at commit 2c56d6b, followed by participant-authentication and staging-access work.',
      basis: 'Production repository history: 2c56d6b, f18b5f8 and 043f4fe.',
      limitation: 'Implementation proves platform capability and delivery progress; it does not by itself establish final participant requirements.',
    },
    {
      id: 'ws-ruok-production-hardening',
      state: 'implemented',
      claim: 'The pilot moved beyond local implementation into staging-access, Magic Link remediation, production Postgres reliability and Launch Candidate content/media integration work.',
      basis: 'Production and LC1 repository history including 0efb911, c6a23a8, 1892158, d57e18b and 72966d4.',
      limitation: 'The source history shows parallel production and LC1 branches at this point; this claim does not collapse that branch state into a fictional single linear release.',
    },
    {
      id: 'ws-ruok-auth-correction',
      state: 'intended',
      claim: 'The later canonical RUOK Product Specification removed mandatory authentication, registration, participant profile and dashboard behaviour from the core campaign journey while retaining authentication as valuable WS27 infrastructure.',
      basis: 'RUOK Product Specification v1: explicit non-requirements and “Keep the engine. Redraw the product around it.”',
      limitation: 'This is a product-architecture correction after technical proof; it does not mean the earlier authentication engineering was wasted or invalid.',
    },

    {
      id: 'casa-examiner-audience',
      state: 'implemented',
      claim: 'The Flight Examiner Rating Course and Professional Development Program served air transport, helicopter and general aviation examiners whose work includes assessing people who train and test other pilots.',
      basis: 'Existing CASA Flight Examiner Rating project record and course metadata.',
      limitation: 'Audience numbers are not published and are not claimed.',
    },
    {
      id: 'casa-reasoning-design',
      state: 'implemented',
      claim: 'The course design centred the reasoning behind regulated assessment rather than treating the program as a restatement of rules.',
      basis: 'Existing CASA project reframe and recovered course evidence.',
      limitation: 'This claim describes the designed learning approach; it does not claim measured behaviour change.',
    },
    {
      id: 'casa-assessment-principles',
      state: 'implemented',
      claim: 'The course explicitly represented validity, reliability, flexibility and objectivity as Principles of Assessment.',
      basis: 'Recovered CASA course screen “Principles of Assessment”.',
    },
    {
      id: 'casa-competency-model',
      state: 'implemented',
      claim: 'The course visualised competency as four dimensions: task skills, task management, contingency management and job-role environment skills.',
      basis: 'Recovered CASA competency iceberg diagram and existing project caption.',
      limitation: 'The artefact supports the model presented in the course; it does not establish evaluation outcomes.',
    },

    {
      id: 'tafe-facilitated-purpose',
      state: 'implemented',
      claim: 'Pathways was designed for facilitator-led Years 8–9 school sessions, deliberately supporting conversation with a TAFE careers adviser rather than replacing that person with self-directed software.',
      basis: 'GH.COM editorial inventory completed August 2026 from Glenn’s project recollection and surviving artefacts.',
      limitation: 'An older portfolio case-study draft described the tool as self-directed; the later inventory is the corrected professional record used here.',
    },
    {
      id: 'tafe-parallel-modes',
      state: 'implemented',
      claim: 'The interface used persistent, non-linear exploration modes including Industry Data, Job Profiles, Slideshow and Summary rather than a required linear lesson sequence.',
      basis: 'Recovered Pathways interface screens and wireframe.',
    },
    {
      id: 'tafe-spatial-exploration',
      state: 'implemented',
      claim: 'Career exploration included a category-filtered interactive map/environment alongside industry data and job profiles.',
      basis: 'Recovered TAFE map and industry-data artefacts.',
      limitation: 'The artefacts demonstrate the interaction design; no usage analytics are claimed.',
    },
    {
      id: 'tafe-stateful-storyline',
      state: 'implemented',
      claim: 'The Pathways build used extensive Storyline variables and JavaScript for dynamically counting industry statistics, contributing to application-like behaviour beyond conventional slide progression.',
      basis: 'August 2026 editorial inventory and Glenn’s implementation recollection.',
      limitation: 'The surviving screenshots do not expose the original variable or JavaScript source code directly.',
    },
  ],
});

export const recordIndex = indexRecordContent(recordContent);
export const workProjects = [...recordContent.projects].sort(
  (a, b) => a.placements.find((p) => p.surface === 'work').order - b.placements.find((p) => p.surface === 'work').order,
);
export const wellbeingProject = recordIndex.projectById['wellbeing-studio-2027'];
export const contextualEntryRecord = recordIndex.recordById['ws-contextual-entry'];
export const dailyWellbeingArtefact = recordIndex.artefactById['ws-daily-wellbeing-journey'];
export const connectedServiceRecord = recordIndex.recordById['ws-connected-service'];
export const connectedServiceArtefact = recordIndex.artefactById['ws-connected-service-map'];
export const ruokProductionRecord = recordIndex.recordById['ws-ruok-production-slice'];
export const ruokProductionArtefact = recordIndex.artefactById['ws-ruok-production-gates'];
export const casaProject = recordIndex.projectById['casa-ferc'];
export const casaJudgementRecord = recordIndex.recordById['casa-examiner-judgement'];
export const casaJudgementArtefact = recordIndex.artefactById['casa-assessment-reasoning-sequence'];
export const casaRecords = casaProject.recordIds.map((id) => recordIndex.recordById[id]);
export const tafeProject = recordIndex.projectById['tafe-pathways'];
export const tafeConversationRecord = recordIndex.recordById['tafe-supported-conversation'];
export const tafeConversationArtefact = recordIndex.artefactById['tafe-facilitated-exploration'];
export const tafeRecords = tafeProject.recordIds.map((id) => recordIndex.recordById[id]);
export const wellbeingRecords = wellbeingProject.recordIds.map((id) => recordIndex.recordById[id]);
export const recordRoutePaths = [
  ...recordContent.records.map((record) => record.path),
  ...recordContent.artefacts.map((artefact) => artefact.path),
];

export const evidenceStateLabel = {
  intended: 'Intended',
  implemented: 'Implemented',
  observed: 'Observed',
  validated: 'Validated',
};
